name: Deploy Mangust Bot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to VPS
        run: |
          ssh root@176.113.82.90 << 'EOF'
          set -e
          systemctl stop mangustbot || true
          cd /root/MangustGPT_Mulberry_mini
          git fetch origin master
          git reset --hard origin/master
          /root/MangustGPT_Mulberry_mini/venv/bin/pip install -r requirements.txt
          systemctl start mangustbot
          EOF
