name: Test SSH to VPS

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 176.113.82.90 >> ~/.ssh/known_hosts

      - name: Run command on VPS
        run: |
          ssh -i ~/.ssh/id_ed25519 root@176.113.82.90 "echo 'Успешное подключение к серверу $(hostname)'"
